server:
  port: 8888

eureka:
  instance:
    nonSecurePort: 8888
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: matcher
      repositories:
        enabled: true
  application:
    name: admin-service
