server:
  port: ${service.port:8888}

spring:
  data:
    mongodb:
      host: ${mongodb.host:localhost}
      port: ${mongodb.port:27017}
      database: ${mongodb.database:matcher}
      repositories:
        enabled: true
